version: '3.8'

services:
  provectio-telecom:
    build: .
    ports:
      - "3015:3015"
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3015"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
